[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "deep_learn_lib"
version = "0.1.0"

description = "A lightweight deep learning library"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
]
